dimensions = dim_struct(0, 0, [], [], 0, 0)

params = parameters(Int64[], 
                    Int64[],
                    [],
                    [],
                    [],
                    [],
                    [],
                    [],
                    [],
                    [],
                    0.01,
                    [],
                    [],
                    0.0,
                    0.0,
                    [],
                    [],
                    [],
                    [],
                    false,
                    false,
                    false,
                    false,
                    0.5,
                    0.5,
                    0,
                    [],
                    [],
                    0)